### ISSUE TITLE
framebuffer

### ISSUE THREAD

**Issue by piranna** [szeged/sprocket#4]
Is it possible to make `sprocket` to render directly to the Linux FBDev framebuffer? Or to EGL?

**Comment by kaadam** [comment]
Hi prianna,

Unfortunately Sprocket does not support these things. Basically this project was not aim to support that the browser application is able to running without windowing system. I'm not an expert but as I see it is possible via ui/ozone. In this case SurfaceFactoryOzone and the OzonePlatform interfaces should be implemented, so Sprocket should have its ozoneplatfrom implementation to handle Linux framebuffer device or EGL directly. 
~3 weeks ago Chromium started to support a headless mode in order to the browser can run without any kind of X: https://bugs.chromium.org/p/chromium/issues/detail?id=546953#c150
Maybe It helps you.

**Comment by piranna** [comment]
I have been following progress on headless mode, probably it will not be too much difficult to adapt it to use the memory region used by Linux framebuffer, so I'll take a look at it :-)
